spring:
  application:
    name: findyourplaces

  datasource:
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true