version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: findyourplaces-db
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "3355:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
